In [3]:
import torch
import numpy as np
import time
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [7]:
%%time 
start_time=time.time()
#matrix operations here
zeros=torch.zeros(1,1)
end_time=time.time()

elapsed_time=end_time-start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [15]:
#define the probability tensor
probabilities=torch.tensor([0.1,0.9])
#10% or 0.1 -> 0, 90% or 0.9 ->1. each probability points to the index of the probability in the tensor
#Draw 5 samples from the multinomial distribution
samples=torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)


tensor([1, 0, 1, 0, 1, 1, 0, 1, 1, 1])


In [16]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat(((tensor,torch.tensor([5]))),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
out=torch.tril(torch.ones(5,5))    #tril means triangular lower 
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out=torch.triu(torch.ones(5,5))  #triu means  triangular upper
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) ==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
input=torch.zeros(2,3,4)
out=input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [24]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
tensor3=torch.tensor([7,8,9])

#stack the tensors along a new dimension
stacked_tensor=torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
import torch.nn as nn
sample=torch.tensor([10.,10.,10.])
linear=nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([-2.0586e-03, -6.5603e+00, -1.6319e-01], grad_fn=<SqueezeBackward4>)


In [29]:
import torch.nn.functional as F 

#Create a tensor
tensor1=torch.tensor([1.0,2.0,3.0])

#Apply softmax using torch.nn.functional.softmax()
softmax_output=F.softmax(tensor1,dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [32]:
#initialize an embedding layer
vocab_size=1000
embedding_dim=100
embedding=nn.Embedding(vocab_size,embedding_dim)

#create some input indices
input_indices=torch.LongTensor([1,5,3,2])

#apply the embedding layer
embedded_output=embedding(input_indices)

#The output will be a tensor of shape (4,100) , where 4 is the number of inputs
#and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 100])
tensor([[-1.2857e+00, -1.3637e+00,  3.2604e-01, -2.5048e+00, -4.2852e-01,
         -6.6480e-02,  4.2917e-01,  4.8664e-01,  1.2663e-01, -6.7752e-01,
          1.1293e+00,  2.2178e+00, -3.4779e-01, -6.6703e-01,  5.9442e-01,
          1.7715e-01,  1.4126e+00, -1.4976e+00, -1.1407e+00, -3.7576e-01,
          1.5969e+00,  3.3346e-01,  1.1257e+00, -1.1514e-01, -2.2819e-02,
          1.3938e+00, -3.2395e-01, -8.3231e-02,  1.4532e+00, -2.9673e-01,
          1.5231e+00, -1.5930e+00,  1.8200e+00,  3.9285e-02,  3.4864e-01,
          4.3790e-01,  2.2291e+00, -8.2229e-01,  8.7891e-01, -1.5321e+00,
         -7.0306e-01, -2.7247e-01, -1.1649e+00,  7.8056e-01, -2.2285e+00,
          5.9678e-01,  4.7906e-01, -1.4118e+00,  5.9636e-02,  1.0458e+00,
          5.0411e-01, -4.2979e-01, -2.9246e-01, -1.1399e+00,  5.9545e-01,
         -1.8473e+00, -6.5427e-01,  5.5846e-01, -1.6102e-01,  7.5331e-01,
          1.0832e+00, -8.4140e-02, -9.4856e-01, -1.6367e+00, -9.9617e-01,
          6.1323e

In [37]:
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
# print(a@b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [38]:
int_64=torch.randint(1,(3,2)).float()
#type int64
float_32=torch.rand(2,3)
#type float32
result=torch.matmul(int_64,float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [29]:
# randint=torch.randint(-100,100,(6,))
# # randint

In [30]:
# tensor=torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
# tensor

In [31]:
# zeros=torch.zeros(2,3)
# zeros

In [32]:
# ones=torch.ones(3,4)
# ones

In [33]:
# input=torch.empty(2,3)
# input

In [34]:
# new=torch.empty(5,8)
# new

In [35]:
# arange=torch.arange(5)
# arange

In [40]:
# linspace=torch.linspace(3,10,steps=5)
# linspace

In [37]:
# logspace=torch.logspace(start=10,end=10,steps=5)
# logspace

In [38]:
# eye=torch.eye(5)
# eye

In [39]:
# a=torch.empty((2,3),dtype=torch.int64)
# empty_like=torch.empty_like(a)
# empty_like